

if (GEOMETRICSPANNERS_INCLUDES AND GEOMETRICSPANNERS_LIBRARIES)
  set(GEOMETRICSPANNERS_FIND_QUIETLY TRUE)
endif (GEOMETRICSPANNERS_INCLUDES AND GEOMETRICSPANNERS_LIBRARIES)

find_path(GEOMETRICSPANNERS_INCLUDES
  NAMES
  GeometricSpanners.cpp
  PATHS
  $ENV{GMPDIR}
  ${INCLUDE_INSTALL_DIR}
  /home/matt/GeometricSpanners/src/
)

find_library(GEOMETRICSPANNERS_LIBRARIES GEOMETRICSPANNERS PATHS /home/matt/GeometricSpanners/src/ $ENV{GEOMETRICSPANNERSDIR} ${LIB_INSTALL_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GEOMETRICSPANNERS DEFAULT_MSG
                                  GEOMETRICSPANNERS_INCLUDES GEOMETRICSPANNERS_LIBRARIES)
mark_as_advanced(GEOMETRICSPANNERS_INCLUDES GEOMETRICSPANNERS_LIBRARIES)
